### ISSUE TITLE
False positive with already there object

### ISSUE THREAD

**Issue by thib5** [robmarkcole/HASS-Deepstack#275]
Hi I install this to make object detection on my camera so I don't have a notification every time a bug pass in front of my camera. the issue is if a bug pass in front of ma camera it trigger a motion detection. Then deep stack analyse it and try to find if there is a car or a person in the picture. but if a car is already present it trigger a notification 

So my setup is pointless it still give me false positive. Is there something I could do to trigger notification only when new object is detected or something like that ? 

Thanks

**Comment by robmarkcole** [comment]
There is not a simple solution to this using deepstack. You could setup an automation to compare new detection to old detection, but this might be sensitive to changes in the scene brightness. Best approach would be to try tweak your motion detection to ignore these bugs

**Comment by vin901** [comment]
Credits to Rob, I actually forked the project and added exactly that feature because I also have parked cars in front of the cameras. So I added 2 new configuration variables:

**prev_objects_ignore**: (optional, default true) Ignore objects if it's bounding box is within prev_objs_pct % difference. Ignored objects are green color.

**prev_objects_pct**: (optional, default 0.02) The percentage plus or minus difference of bounding box to be ignored if prev_objs_ignore set to true.

It's fairly simple but it works for me with the default values, it just remembers the previous detected objects and when it's triggered again it compares the bounding box of the new objects, if it's within the percentage difference of the old detected objects then it gets highlighted in green but only triggers if there is at least 1 new object detected (red).

https://github.com/vin901/HASS-Deepstack-object

**Comment by thib5** [comment]
Wow ! This is. exactly what I need ! I willl give it a try !

Thanks

**Comment by robmarkcole** [comment]
@vin901 can I persuade you to make a pull request with this feature?

**Comment by vin901** [comment]
@robmarkcole yeah sure, although I've never done a pull request before and usually I just fork projects for my own use. So let me know what I need to do to merge it. I also made a couple of other changes, but they  should probably be separate pull requests, so where can I post/discuss?

**Comment by robmarkcole** [comment]
@vin901 you will need a separate branch for each PR, then just create against here
